vich_uploader:
    db_driver: orm

    mappings:
        legumeImg:
            uri_prefix: /images/legumes
            upload_destination: '%kernel.project_dir%/public/images/legumes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 
