vich_uploader:
    db_driver: orm

    mappings:
        legume_image:
            uri_prefix: /img/legumes
            upload_destination: '%kernel.project_dir%/public/img/legumes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 
